#!/usr/bin/env ruby
require 'httparty'

urls = ARGV
urls.each do |url|
  filename = url.sub(/https?\:(\\\\|\/\/)(www.)?/,'')

  File.open("#{filename}.html", "w") do |file|
    response = HTTParty.get(url)
    html = CGI.unescapeHTML(response.parsed_response)

    file.write(html)
  end
  rescue => e
    puts "Something wrong"
end
